spring.application.name=daka-crm
server.port=8080

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/daka
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update

#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#JWT
jwt.secret=secretKey
jwt.accessExpirationMinutes=25
jwt.refreshExpirationMinutes=43200

#Email
mailgun.api.key=3bc1476c9f05ccab3f55a3013d0ecb38-5dcb5e36-f2242cae

#Stripe
stripe.publish.key=pk_test_51IKQbmF87Y56UerjUpytRBOmTyAXc5nBtvZKl62OyKFm5fQ0u08yPSPEAZdnRs2czoxfrE3WAGj1hMFdg6BdwDvr00M62xa7F9
stripe.secret.key=sk_test_51IKQbmF87Y56UerjXtM1alhzNXjw850sBrLrdsX32hYUCTdrFEgWqxb6rSEkEpo6CUw3lzLAuckgTrq0k3XPlC8V00Y5QmE9WS
